name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    uses: ./.github/workflows/common.yml
    steps:
      - name: Run ESLint
        run: npm run lint | tee dist/lint-report.log

      - name: Upload lint results
        uses: actions/upload-artifact@v4
        with:
          name: lint-results
          path: dist/lint-report.log

      - name: TypeScript type check
        run: npm run ts-check | tee dist/ts-check-report.log

      - name: Upload type check results
        uses: actions/upload-artifact@v4
        with:
          name: type-check-results
          path: dist/ts-check-report.log

  tests:
    uses: ./.github/workflows/common.yml
    needs: [lint]
    steps:
      - name: Run tests
        run: npm run test:ci

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: dist/tests-report.xml

  build:
    uses: ./.github/workflows/common.yml
    needs: [tests, lint]
    steps:
      - name: Run build
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: dist/
